server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/redis_pagination_service_db?createDatabaseIfNotExist=true
    username: root
    password: password

#  cache:
#    redis:
#      time-to-live: 600000
#
#  redis:
#    database: 0
#    port: 6379
#    host: localhost

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
  #        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER